#!/bin/sh


#CFLAGS_NEW="-DDEBUG_WOLFSSL -DWOLFSSL_USER_SETTINGS"
CFLAGS_NEW="-DWOLFSSL_USER_SETTINGS"
export CFLAGS="${CFLAGS} ${CFLAGS_NEW}"

make -f sgx_t_static.mk HAVE_WOLFSSL_BENCHMARK=1 HAVE_WOLFSSL_TEST=1 HAVE_WOLFSSL_SP=1

